### ISSUE TITLE
Help how to send command MMS ?

### ISSUE THREAD

**Issue by Andrii10** [beanit/iec61850bean#15]
Hello.
I need your help. How send the command MMS from this library to device. On this a dataset dev0E0DLDCTRL/MMSRECGGIO1$CF$SPCS01$ctlVal

**Comment by MoheyEl-DinBadr** [comment]
As I see the point is a CF which is configuration and not a command so I guess the change of value will be enough
And If possible send me the SCL file to have a further inspection.

**Comment by Andrii10** [comment]
[INIT.txt](https://github.com/beanit/iec61850bean/files/5350375/INIT.txt)
This is my file , Dataset4 is about command MMS

**Comment by Andrii10** [comment]
This is a foto, send command MMS in another programm 
![image](https://user-images.githubusercontent.com/29731103/95593226-16243600-0a52-11eb-9fd5-b00f4c6cf3d8.png)

**Comment by MoheyEl-DinBadr** [comment]
you should do something like 
ModelNode fcModelNode2 = serverModel.findModelNode("dev0E0DLDCTRL/MMSRECGGIO1.SPCSO1.ctlVal",Fc.CF);
            Integer vall = 1;
            ((BdaInt8)fcModelNode2).setValue(vall.byteValue());
            association.setDataValues((FcModelNode) fcModelNode2);

and by the way, this is not a command it is just a change of configuration the command should have a FC of CO

**Comment by MoheyEl-DinBadr** [comment]
One more thing, It is not recommended to add the command to a dataSet

**Comment by Andrii10** [comment]
After ModelNode fcModelNode2 = serverModel.findModelNode("dev0E0DLDCTRL/MMSRECGGIO1.SPCSO1.ctlVal",Fc.CF);
        Integer vall = 1;
        ((BdaInt8)fcModelNode2).setValue(vall.byteValue());
        try {
            association.setDataValues((FcModelNode) fcModelNode2);
        } catch (ServiceError serviceError) {
            serviceError.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
I take a exception :
com.beanit.iec61850bean.ServiceError: Service error: ACCESS_VIOLATION(3) MMS DataAccessError: object-access-denied
	at com.beanit.iec61850bean.ClientAssociation.mmsDataAccessErrorToServiceError(ClientAssociation.java:175)
	at com.beanit.iec61850bean.ClientAssociation.decodeSetDataValuesResponse(ClientAssociation.java:1164)
	at com.beanit.iec61850bean.ClientAssociation.setDataValues(ClientAssociation.java:1115)
	at com.promavtomatica.iec61850.Iec61850Application.main(Iec61850Application.java:106)

**Comment by MoheyEl-DinBadr** [comment]
The ACCESS_VIOLATION exception is a response from the IED and the reason may be because one of these
1- Your client is not defined or recognized by the IED to give commands.
2- There is an Interlock that is blocking you from issuing the command.
3- The command is not a direct command and it is an SBO (select before operate command).
So please check those 3 first but I exclude the 3rd option based on the SCL file.

**Comment by Andrii10** [comment]
Thank you
