### ISSUE TITLE
[Help] Example with SSLSocketFactory

### ISSUE THREAD

**Issue by mschreiber** [beanit/iec61850bean#17]
An example for creating a connection using TLS would be great. If I pass the SSLSocketFactory
```java
ClientSap clientSap = new ClientSap(SSLSocketFactory.getDefault());
```
it works, but the server, which does an TPDU Header version check rejects the connection saying that he expects TPDU Header version 3 but got 16.

**Comment by sfeuerhahn** [comment]
That is strange. the stack always sends version 3.
