### ISSUE TITLE
ClientAssociation: get a bit in servicesSupported from InitiateResponsePDU

### ISSUE THREAD

**Issue by pavel-ch** [beanit/iec61850bean#21]
In a client, I want to check the server's ability to define a `NamedVariableList` prior to any tries to do it. With other client libraries this works well.
There is a bit flag `defineNamedVariableList` inside sevicesSupported bitstring returned by `initiateResponsePdu.getInitResponseDetail().getServicesSupportedCalled()`, but the holding variable (`byte[] servicesSupported`) is local in the `ClientAssociation.handleInitiateResponse()` method.
Can I make the variable `byte[] servicesSupported` a private field in `ClientAssociation`, make a public getter to it and create a PR?

**Comment by sfeuerhahn** [comment]
thanks for the contribution
