### ISSUE TITLE
What is mean the feture of  "Buffered reporting (client only)" ?

### ISSUE THREAD

**Issue by Xc2333** [beanit/iec61850bean#24]
Hi! First of all, thank you very much for this open source project, it really helped me a lot, but I have some questions and puzzles about the Buffered Report. According to the help document, I saw Client Only. I want to know that this means that the buffering work is done by the client or does the client control the server to complete the buffering function configuration?  

> IEC61850bean supports the following IEC 61850 services:
> 
> All GetDirectory and GetDataDefinition services
> GetDataValues and SetDataValues
> Data set services
> Unbuffered reporting
> **Buffered reporting (client only)**
> Control services

**Comment by sfeuerhahn** [comment]
The buffering is always done by the server. But IEC61850bean cannot be used to implement servers that buffer data. But it can be used to implement clients that access servers that buffer reports.

**Comment by Xc2333** [comment]
> The buffering is always done by the server. But IEC61850bean cannot be used to implement servers that buffer data. But it can be used to implement clients that access servers that buffer reports.

So,that's mean IEC61850bean doesn't has the function of bufferring data? If true, so why  and how to do it by some other way? Thx.
